# Site settings
title: "Old School Software Engineer and Thinker since the 80s"
description: "Please help me not become homeless. Please. Please. Please."
baseurl: ""
url: "http://youlian.github.io"

# Build settings
markdown: kramdown
permalink: pretty
highlighter: pygments
paginate: 3

# Links
links:
  - title: "abt"
    url: /about
  - title: "twt"
    url: http://twitter.com/_youlian
  - title: "git"
    url: http://github.com/youlian

